---
# tasks file for /etc/ansible/roles/backup-image
- name: Récupération des variables "ansible_date_time" de ansible
  setup:
    filter: "ansible_date_time"
    gather_subset: "!all"

- name: Récupération des facts IOS
  cisco.ios.ios_facts:

- name: Configuration de l'accès au serveur "SRV-FTP"
  cisco.ios.ios_config:
    lines:
      - "ip ftp username {{ ftp_username }}"
      - "ip ftp password {{ ftp_password }}"
      - "file prompt quiet"

- name: Sauvegarde de l'image vers le serveur "SRV-FTP"
  cisco.ios.ios_command:
    commands:
      - "copy {{ ansible_net_image }} ftp://{{ ftp_ip_address }}/image/{{ device_name }}.image.{{ ansible_date_time.date }}.{{ ansible_date_time.time }}.bin"